# Generated by Django 3.2.9 on 2021-11-25 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-publishdate']},
        ),
    ]
